apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
//apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-kapt'

def rootProject = project.rootProject

android {
    signingConfigs {
    }
    compileSdk 36
    Properties properties = new Properties()
    properties.load(rootProject.file("local.properties").newDataInputStream())
    defaultConfig {
        applicationId "jp.co.yuji.mydebugapplication"
        minSdkVersion 24
        targetSdkVersion 36
        buildToolsVersion = "36.0.0"
        versionCode 33
        versionName "1.14.0"
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
        vectorDrawables.useSupportLibrary = true
        multiDexEnabled true

        resValue "string", "app_id", properties.getProperty("app_id", "")
        resValue "string", "app_info_bottom_unit_id", properties.getProperty("app_info_bottom_unit_id", "")
        resValue "string", "hardware_info_bottom_unit_id", properties.getProperty("hardware_info_bottom_unit_id", "")
        resValue "string", "other_info_bottom_unit_id", properties.getProperty("other_info_bottom_unit_id", "")
    }
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = "17"
    }
    buildFeatures {
        dataBinding = true
        viewBinding = true
    }
    namespace 'jp.co.yuji.mydebugapplication'
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation 'androidx.appcompat:appcompat:1.8.0'
    implementation 'androidx.recyclerview:recyclerview:1.4.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.2'
    implementation 'androidx.vectordrawable:vectordrawable:1.2.0'
    implementation 'androidx.browser:browser:1.10.0'
    implementation 'androidx.media:media:1.8.0'
    implementation 'com.google.android.material:material:1.14.0'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.11.0'
    implementation 'com.android.support:multidex:1.0.3'

    implementation 'com.google.firebase:firebase-core:21.1.1'
//    implementation 'com.google.firebase:firebase-ads:20.1.0'

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test:runner:1.7.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.7.0'
    constraints {
        implementation('androidx.work:work-runtime:2.11.2') {
            because 'previous versions have a bug impacting this application'
        }
    }
    implementation("com.google.android.libraries.ads.mobile.sdk:ads-mobile-sdk:1.4.0")
}
apply plugin: 'com.google.gms.google-services'
